name: Simbirsoft SDET task 1

on:
  push:
    branches: [api_tests, mocking]
  pull_request:
    branches: [api_tests]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Cache Allure CLI
        uses: actions/cache@v4
        id: cache-allure
        with:
          path: allure/
          key: allure-2.35.1
      
      - name: Download Allure CLI
        if: steps.cache-allure.outputs.cache-hit != 'true'
        run: |
          curl -o allure-2.35.1.zip -L https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
          unzip allure-2.35.1.zip -d allure
          chmod +x allure/allure-2.35.1/bin/allure
         
      - name: Run tests
        run: |
          pytest -n auto --alluredir=./allure-results

      - name: Generate Allure report
        if: always()
        run: |
          allure/allure-2.35.1/bin/allure generate allure-results -o allure-report --clean
      
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 1
